# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hl-shop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2af5777336664aa7a9b9baa7b5d02503 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2df56f43109a49d3ba59d7a589a0c692 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2af5777336664aa7a9b9baa7b5d02503 }}/hlshop:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hl-shop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2029e4d60287407492311dc618c6474c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2af5777336664aa7a9b9baa7b5d02503 }}/hlshop:${{ github.sha }}'